#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1E953E27D4311E58 (lamby@gnu.org)
#
Name     : diffoscope
Version  : 108
Release  : 60
URL      : https://files.pythonhosted.org/packages/45/33/d80f0f61e601fb9de7630b92bc8f88e8ecb5218858e000e00bc7510317c9/diffoscope-108.tar.gz
Source0  : https://files.pythonhosted.org/packages/45/33/d80f0f61e601fb9de7630b92bc8f88e8ecb5218858e000e00bc7510317c9/diffoscope-108.tar.gz
Source99 : https://files.pythonhosted.org/packages/45/33/d80f0f61e601fb9de7630b92bc8f88e8ecb5218858e000e00bc7510317c9/diffoscope-108.tar.gz.asc
Summary  : Tool for in-depth comparison of files, archives, and directories
Group    : Development/Tools
License  : GPL-3.0
Requires: diffoscope-bin = %{version}-%{release}
Requires: diffoscope-license = %{version}-%{release}
Requires: diffoscope-python = %{version}-%{release}
Requires: diffoscope-python3 = %{version}-%{release}
Requires: argcomplete
Requires: defusedxml
Requires: distro
Requires: jsondiff
Requires: libarchive-c
Requires: progressbar
Requires: python-magic
Requires: pyxattr
BuildRequires : buildreq-distutils3
BuildRequires : libarchive-c
BuildRequires : libarchive-dev
BuildRequires : python-magic
BuildRequires : python-rpm

%description
diffoscope
==========
.. only:: not manpage
.. image:: https://badge.fury.io/py/diffoscope.svg
:target: http://badge.fury.io/py/diffoscope

%package bin
Summary: bin components for the diffoscope package.
Group: Binaries
Requires: diffoscope-license = %{version}-%{release}

%description bin
bin components for the diffoscope package.


%package license
Summary: license components for the diffoscope package.
Group: Default

%description license
license components for the diffoscope package.


%package python
Summary: python components for the diffoscope package.
Group: Default
Requires: diffoscope-python3 = %{version}-%{release}

%description python
python components for the diffoscope package.


%package python3
Summary: python3 components for the diffoscope package.
Group: Default
Requires: python3-core

%description python3
python3 components for the diffoscope package.


%prep
%setup -q -n diffoscope-108

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547651771
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/diffoscope
cp COPYING %{buildroot}/usr/share/package-licenses/diffoscope/COPYING
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/diffoscope

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/diffoscope/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
